#!/bin/bash

SELF_DIR=$(git rev-parse --show-toplevel)
PERMISSIONS=${SELF_DIR}/.permissions

echo -n "Restoring file permissions..."

IFS_OLD=${IFS}; IFS=$'\n'
while read -r LINE || [[ -n "$LINE" ]] ; do
   FILE=${LINE/;*/}
   MODE=${LINE/*;/}
   # Set the file permissions
   chmod ${MODE} ${FILE}
done < ${PERMISSIONS}
IFS=${IFS_OLD}

echo "OK"

exit 0