#!/bin/bash
#
# A hook script called by "git commit" with no arguments. The hook should
# exit with non-zero status after issuing an appropriate message if it wants
# to stop the commit.

SELF_DIR=$(git rev-parse --show-toplevel)
PERMISSIONS=${SELF_DIR}/.permissions

# Clear the permissions database file
> ${PERMISSIONS}

echo -n "Backing-up file permissions..."

IFS_OLD=$IFS; IFS=$'\n'
for FILE in $(git ls-tree HEAD -dr --name-only; git ls-files) ; do
   # Save the permissions of all the files in the index
   echo "${FILE};$(stat -c %a ${FILE})" >> ${PERMISSIONS}
done
IFS=$IFS_OLD

# Add the permissions database file to the index
git add ${PERMISSIONS}

echo "OK"